"""
Create Engine 1: LSTM + XGBoost with ML Pattern Recognition + Smart SL
Complete notebook from scratch with powerful pattern analysis system
"""

import json
from pathlib import Path

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "id": "title",
            "metadata": {},
            "source": ["# Engine 1: LSTM + XGBoost\n", "## ML Pattern Recognition + Smart Stop Loss\n", "\n",
                      "**Strategy:**\n", "- LSTM (54%) + XGBoost (57%) ensemble → direction + confidence\n",
                      "- ML Pattern Recognition → 8 candlestick patterns + support/resistance + breakouts\n",
                      "- Smart Stop Loss → Volatility-adjusted, pattern-optimized, support-based\n",
                      "- Multi-timeframe confirmation (1H + 4H + 1D)\n", "\n",
                      "**Expected:** Better predictions + tighter SL + higher win rate"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "imports",
            "metadata": {},
            "outputs": [],
            "source": [
                "import sys, os, warnings, threading, time, json, pickle\n",
                "warnings.filterwarnings('ignore')\n",
                "ROOT = os.path.abspath('..')\n",
                "if ROOT not in sys.path:\n",
                "    sys.path.insert(0, ROOT)\n",
                "\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import tensorflow as tf\n",
                "import yfinance as yf\n",
                "from pathlib import Path\n",
                "from datetime import datetime, timezone\n",
                "\n",
                "from src.data_feeds import fetch_multi_timeframe, SYMBOL_MAP\n",
                "from src.feature_engineering import compute_features\n",
                "from src.regime_detector import RegimeDetector\n",
                "from src.pattern_detector import PatternDetector\n",
                "from src.ml_pattern_recognizer import ChartPatternMLDetector\n",
                "\n",
                "plt.rcParams.update({'figure.dpi': 120, 'axes.grid': True, 'grid.alpha': 0.25})\n",
                "print('[OK] Imports complete')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "config",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# CONFIG: EDIT THIS SECTION ONLY\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "ASSET = 'XAUUSD'\n",
                "ENTRY_TF = '1H'\n",
                "CONFIRM_TF = '4H'  # Multi-TF confirmation\n",
                "\n",
                "TRAIN_BARS = 200\n",
                "FORECAST_H = 1\n",
                "\n",
                "# Risk Management\n",
                "ACCOUNT_BALANCE = 1000.0\n",
                "MAX_RISK_PCT = 0.01  # 1% per trade\n",
                "RR_RATIO = 2.0  # 1:2 reward:risk\n",
                "MIN_RR = 1.5\n",
                "\n",
                "# Confidence thresholds\n",
                "BASE_CONFIDENCE = 55  # Base threshold\n",
                "HIGH_CONFIDENCE = 75  # For tight SL\n",
                "\n",
                "# Pattern recognition\n",
                "USE_PATTERN_RECOGNITION = True\n",
                "USE_ML_PATTERNS = True\n",
                "MIN_PATTERN_QUALITY = 0.6  # 0-1 score\n",
                "\n",
                "# Smart SL settings\n",
                "USE_SMART_SL = True\n",
                "SL_REDUCTION_TIGHT = 0.7  # 30% tighter with high confidence\n",
                "SL_REDUCTION_PATTERN = 0.6  # 40% tighter with good pattern\n",
                "\n",
                "# Live scanning\n",
                "LIVE = False\n",
                "SCAN_INTERVAL_S = 500\n",
                "\n",
                "print(f'[CONFIG] {ASSET} {ENTRY_TF} | Risk={MAX_RISK_PCT:.1%} | R:R={RR_RATIO}:1')\n",
                "print(f'[CONFIG] Pattern Recognition: {\"ON\" if USE_PATTERN_RECOGNITION else \"OFF\"}')\n",
                "print(f'[CONFIG] Smart SL: {\"ON\" if USE_SMART_SL else \"OFF\"}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "load_models",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# LOAD LSTM + XGBOOST MODELS\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "_lstm_model = None\n",
                "_lstm_scaler = None\n",
                "_lstm_features = None\n",
                "_xgb_model = None\n",
                "_xgb_scaler = None\n",
                "_xgb_features = None\n",
                "\n",
                "def load_lstm():\n",
                "    global _lstm_model, _lstm_scaler, _lstm_features\n",
                "    try:\n",
                "        model_path = Path('../results/advanced_models/best_model_lstm_final.h5')\n",
                "        scaler_path = Path('../results/advanced_models/scaler_final.pkl')\n",
                "        meta_path = Path('../results/advanced_models/metadata.json')\n",
                "        \n",
                "        _lstm_model = tf.keras.models.load_model(str(model_path))\n",
                "        with open(scaler_path, 'rb') as f:\n",
                "            _lstm_scaler = pickle.load(f)\n",
                "        with open(meta_path, 'r') as f:\n",
                "            meta = json.load(f)\n",
                "            _lstm_features = meta.get('features', [])\n",
                "        \n",
                "        print(f'[OK] LSTM loaded: {len(_lstm_features)} features, 54.0% accuracy')\n",
                "        return True\n",
                "    except Exception as e:\n",
                "        print(f'[ERROR] LSTM load failed: {e}')\n",
                "        return False\n",
                "\n",
                "def load_xgboost():\n",
                "    global _xgb_model, _xgb_scaler, _xgb_features\n",
                "    try:\n",
                "        model_path = Path('../results/advanced_models/best_model_xgb_final.pkl')\n",
                "        scaler_path = Path('../results/advanced_models/scaler_final.pkl')\n",
                "        meta_path = Path('../results/advanced_models/metadata.json')\n",
                "        \n",
                "        with open(model_path, 'rb') as f:\n",
                "            _xgb_model = pickle.load(f)\n",
                "        with open(scaler_path, 'rb') as f:\n",
                "            _xgb_scaler = pickle.load(f)\n",
                "        with open(meta_path, 'r') as f:\n",
                "            meta = json.load(f)\n",
                "            _xgb_features = meta.get('features', [])\n",
                "        \n",
                "        print(f'[OK] XGBoost loaded: {len(_xgb_features)} features, 57.2% accuracy')\n",
                "        return True\n",
                "    except Exception as e:\n",
                "        print(f'[ERROR] XGBoost load failed: {e}')\n",
                "        return False\n",
                "\nlstm_ok = load_lstm()\nxgb_ok = load_xgboost()\n",
                "print(f'\\n[STATUS] Models: LSTM={lstm_ok} XGBoost={xgb_ok}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "pattern_recognition",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# ML PATTERN RECOGNITION SYSTEM\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "class MLPatternEngine:\n",
                "    '''Advanced pattern recognition for trading signals'''\n",
                "    \n",
                "    def __init__(self):\n",
                "        self.pattern_detector = PatternDetector(lookback=50)\n",
                "        self.ml_detector = ChartPatternMLDetector()  # 8 candlestick patterns\n",
                "    \n",
                "    def detect_candlestick_patterns(self, df):\n",
                "        '''Detect: Engulfing, Harami, Hammer, Shooting Star, Morning Star, Evening Star'''\n",
                "        patterns = {}\n",
                "        if len(df) < 3:\n",
                "            return patterns\n",
                "        \n",
                "        o, h, l, c = df['open'].values, df['high'].values, df['low'].values, df['close'].values\n",
                "        \n",
                "        # Engulfing\n",
                "        bullish_eng = (c[-1] > o[-1]) and (c[-1] > h[-2]) and (o[-1] < l[-2])\n",
                "        bearish_eng = (c[-1] < o[-1]) and (c[-1] < l[-2]) and (o[-1] > h[-2])\n",
                "        patterns['engulfing'] = {'bullish': bullish_eng, 'bearish': bearish_eng}\n",
                "        \n",
                "        # Hammer (long lower wick, small body)\n",
                "        body = abs(c[-1] - o[-1])\n",
                "        wick_low = min(o[-1], c[-1]) - l[-1]\n",
                "        hammer = (wick_low > body * 2) and (body / (h[-1] - l[-1]) < 0.3)\n",
                "        patterns['hammer'] = hammer\n",
                "        \n",
                "        # Shooting star\n",
                "        wick_high = h[-1] - max(o[-1], c[-1])\n",
                "        shooting_star = (wick_high > body * 2) and (body / (h[-1] - l[-1]) < 0.3)\n",
                "        patterns['shooting_star'] = shooting_star\n",
                "        \n",
                "        # Morning/Evening star\n",
                "        if len(df) >= 3:\n",
                "            gap_up = l[-1] > h[-2]\n",
                "            patterns['morning_star'] = gap_up and (c[-1] > c[-3])\n",
                "            patterns['evening_star'] = (l[-1] < h[-2]) and (c[-1] < c[-3])\n",
                "        \n",
                "        return patterns\n",
                "    \n",
                "    def detect_support_resistance(self, df, lookback=50):\n",
                "        '''Detect support/resistance levels and proximity'''\n",
                "        if len(df) < lookback:\n",
                "            return None, None, 0\n",
                "        \n",
                "        recent = df.iloc[-lookback:]\n",
                "        support = recent['low'].min()\n",
                "        resistance = recent['high'].max()\n",
                "        cur_price = float(df['close'].iloc[-1])\n",
                "        \n",
                "        dist_to_support = (cur_price - support) / (resistance - support) if resistance > support else 0.5\n",
                "        \n",
                "        return support, resistance, dist_to_support\n",
                "    \n",
                "    def detect_breakout(self, df, lookback=30):\n",
                "        '''Detect breakout above resistance or below support'''\n",
                "        if len(df) < lookback + 1:\n",
                "            return None\n",
                "        \n",
                "        prev = df.iloc[-(lookback+1):-1]\n",
                "        prev_high = prev['high'].max()\n",
                "        prev_low = prev['low'].min()\n",
                "        \n",
                "        cur_high = float(df['high'].iloc[-1])\n",
                "        cur_low = float(df['low'].iloc[-1])\n",
                "        \n",
                "        breakout_up = cur_high > prev_high\n",
                "        breakout_down = cur_low < prev_low\n",
                "        \n",
                "        return {'breakout_up': breakout_up, 'breakout_down': breakout_down, \n",
                "                'prev_high': prev_high, 'prev_low': prev_low}\n",
                "    \n",
                "    def pattern_quality_score(self, patterns):\n",
                "        '''Score patterns 0-1: higher = more reliable'''\n",
                "        score = 0\n",
                "        count = 0\n",
                "        \n",
                "        for pattern_name, pattern_val in patterns.items():\n",
                "            if isinstance(pattern_val, dict):\n",
                "                bullish = pattern_val.get('bullish', False)\n",
                "                bearish = pattern_val.get('bearish', False)\n",
                "                if bullish or bearish:\n",
                "                    score += 1\n",
                "                    count += 1\n",
                "            elif pattern_val:\n",
                "                score += 1\n",
                "                count += 1\n",
                "        \n",
                "        return score / max(count, 1) if count > 0 else 0\n",
                "\npattern_engine = MLPatternEngine()\nprint('[OK] Pattern Recognition Engine initialized')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "smart_sl",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# SMART STOP LOSS SYSTEM\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "def calculate_atr(df, period=14):\n",
                "    '''Calculate Average True Range'''\n",
                "    high = df['high'].values\n",
                "    low = df['low'].values\n",
                "    close = df['close'].values\n",
                "    \n",
                "    tr1 = high - low\n",
                "    tr2 = abs(high - np.roll(close, 1))\n",
                "    tr3 = abs(low - np.roll(close, 1))\n",
                "    \n",
                "    tr = np.maximum(tr1, np.maximum(tr2, tr3))\n",
                "    atr = pd.Series(tr).rolling(period).mean().iloc[-1]\n",
                "    return float(atr) if not np.isnan(atr) else 0.0\n",
                "\n",
                "def smart_stop_loss(df, signal_direction, confidence, pattern_quality, support_level):\n",
                "    '''\n",
                "    Calculate smart SL based on:\n",
                "    - Volatility (ATR)\n",
                "    - Pattern quality\n",
                "    - Confidence level\n",
                "    - Support/Resistance\n",
                "    '''\n",
                "    cur_price = float(df['close'].iloc[-1])\n",
                "    atr = calculate_atr(df)\n",
                "    \n",
                "    # Base SL: ATR-based\n",
                "    base_sl_mult = 1.0\n",
                "    if signal_direction == 1:  # BUY\n",
                "        base_sl = cur_price - atr * base_sl_mult\n",
                "    else:  # SELL\n",
                "        base_sl = cur_price + atr * base_sl_mult\n",
                "    \n",
                "    # Tighten based on confidence\n",
                "    conf_factor = 1.0 - (confidence - 50) / 100 * 0.3\n",
                "    sl_by_confidence = cur_price - (cur_price - base_sl) * conf_factor if signal_direction == 1 else cur_price + (base_sl - cur_price) * conf_factor\n",
                "    \n",
                "    # Tighten based on pattern quality\n",
                "    if pattern_quality > 0.6:\n",
                "        sl_by_pattern = cur_price - (cur_price - sl_by_confidence) * 0.8 if signal_direction == 1 else cur_price + (sl_by_confidence - cur_price) * 0.8\n",
                "    else:\n",
                "        sl_by_pattern = sl_by_confidence\n",
                "    \n",
                "    # Use support/resistance if available and closer\n",
                "    if support_level and signal_direction == 1:\n",
                "        if support_level < sl_by_pattern:\n",
                "            final_sl = support_level - atr * 0.2  # Small buffer below support\n",
                "        else:\n",
                "            final_sl = sl_by_pattern\n",
                "    else:\n",
                "        final_sl = sl_by_pattern\n",
                "    \n",
                "    return final_sl, atr\n",
                "\nprint('[OK] Smart SL System initialized')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "ensemble_forecast",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# ENSEMBLE FORECAST (LSTM + XGBOOST)\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "def run_lstm_prediction(df):\n",
                "    '''Run LSTM on last complete bar'''\n",
                "    if _lstm_model is None:\n",
                "        return None\n",
                "    try:\n",
                "        feat_df = compute_features(df)\n",
                "        feat_clean = feat_df.dropna()\n",
                "        if feat_clean.empty:\n",
                "            return None\n",
                "        \n",
                "        X_raw = feat_clean[_lstm_features].iloc[-1:].values\n",
                "        X_scaled = _lstm_scaler.transform(X_raw)\n",
                "        X_scaled = X_scaled.reshape((1, 1, -1))\n",
                "        \n",
                "        pred = float(_lstm_model.predict(X_scaled, verbose=0)[0, 0])\n",
                "        return pred\n",
                "    except Exception as e:\n",
                "        print(f'[LSTM ERROR] {e}')\n",
                "        return None\n",
                "\n",
                "def run_xgboost_prediction(df):\n",
                "    '''Run XGBoost on last complete bar'''\n",
                "    if _xgb_model is None:\n",
                "        return None\n",
                "    try:\n",
                "        feat_df = compute_features(df)\n",
                "        feat_clean = feat_df.dropna()\n",
                "        if feat_clean.empty:\n",
                "            return None\n",
                "        \n",
                "        X_raw = feat_clean[_xgb_features].iloc[-1:].values\n",
                "        X_scaled = _xgb_scaler.transform(X_raw)\n",
                "        \n",
                "        pred = float(_xgb_model.predict_proba(X_scaled)[0, 1])\n",
                "        return pred\n",
                "    except Exception as e:\n",
                "        print(f'[XGBOOST ERROR] {e}')\n",
                "        return None\n",
                "\n",
                "def ensemble_forecast(df):\n",
                "    '''Combine LSTM (40%) + XGBoost (60%)'''\n",
                "    lstm_pred = run_lstm_prediction(df)\n",
                "    xgb_pred = run_xgboost_prediction(df)\n",
                "    \n",
                "    if lstm_pred is None or xgb_pred is None:\n",
                "        return None\n",
                "    \n",
                "    ensemble_pred = lstm_pred * 0.4 + xgb_pred * 0.6\n",
                "    confidence = abs(ensemble_pred - 0.5) * 200\n",
                "    direction = 1 if ensemble_pred > 0.5 else -1\n",
                "    \n",
                "    return {\n",
                "        'direction': direction,\n",
                "        'ensemble_pred': ensemble_pred,\n",
                "        'lstm_pred': lstm_pred,\n",
                "        'xgb_pred': xgb_pred,\n",
                "        'confidence': min(confidence, 95),\n",
                "    }\n",
                "\nprint('[OK] Ensemble Forecast System initialized')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "fetch_data",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# FETCH LIVE DATA\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "print(f'\\nFetching {ASSET} data...')\n",
                "tf_data = fetch_multi_timeframe(ASSET, [ENTRY_TF, CONFIRM_TF, '1D'], bars=500)\n",
                "\n",
                "for tf, df in tf_data.items():\n",
                "    print(f'  {tf:6s}: {len(df):4d} bars | Last: {df[\"close\"].iloc[-1]:.5f}')\n",
                "\n",
                "entry_df = tf_data[ENTRY_TF]\n",
                "confirm_df = tf_data.get(CONFIRM_TF, entry_df)\n",
                "print(f'\\n[READY] Data loaded for {ASSET}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "generate_signal",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# GENERATE TRADING SIGNAL\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "print('\\n' + '='*70)\n",
                "print('SIGNAL GENERATION')\n",
                "print('='*70)\n",
                "\n",
                "# 1. ML Ensemble Forecast\n",
                "print('\\n[1] Running ML Ensemble Forecast...')\n",
                "fc = ensemble_forecast(entry_df)\n",
                "if fc is None:\n",
                "    print('[ERROR] Ensemble forecast failed')\n",
                "else:\n",
                "    signal = 'BUY' if fc['direction'] > 0 else 'SELL'\n",
                "    print(f'    Direction: {signal}')\n",
                "    print(f'    Confidence: {fc[\"confidence\"]:.0f}% (LSTM: {fc[\"lstm_pred\"]:.2%} | XGBoost: {fc[\"xgb_pred\"]:.2%})')\n",
                "\n",
                "# 2. Pattern Recognition\n",
                "print('\\n[2] Pattern Recognition...')\n",
                "patterns = pattern_engine.detect_candlestick_patterns(entry_df)\n",
                "support, resistance, dist_to_support = pattern_engine.detect_support_resistance(entry_df)\n",
                "breakout = pattern_engine.detect_breakout(entry_df)\n",
                "pattern_quality = pattern_engine.pattern_quality_score(patterns)\n",
                "\n",
                "print(f'    Candlestick Patterns: {pattern_quality:.1%} quality')\n",
                "if patterns.get('engulfing', {}).get('bullish'):\n",
                "    print(f'      - Bullish Engulfing [STRONG]')\n",
                "if patterns.get('engulfing', {}).get('bearish'):\n",
                "    print(f'      - Bearish Engulfing [STRONG]')\n",
                "if patterns.get('hammer'):\n",
                "    print(f'      - Hammer [REVERSAL]')\n",
                "if patterns.get('shooting_star'):\n",
                "    print(f'      - Shooting Star [REVERSAL]')\n",
                "\n",
                "print(f'    Support: {support:.5f} | Resistance: {resistance:.5f} | Distance: {dist_to_support:.1%}')\n",
                "if breakout:\n",
                "    if breakout['breakout_up']:\n",
                "        print(f'      - Breakout UP above {breakout[\"prev_high\"]:.5f}')\n",
                "    if breakout['breakout_down']:\n",
                "        print(f'      - Breakout DOWN below {breakout[\"prev_low\"]:.5f}')\n",
                "\n",
                "# 3. Multi-TF Confirmation\n",
                "print('\\n[3] Multi-Timeframe Confirmation...')\n",
                "fc_confirm = ensemble_forecast(confirm_df)\n",
                "if fc_confirm:\n",
                "    confirm_signal = 'BUY' if fc_confirm['direction'] > 0 else 'SELL'\n",
                "    agree = (confirm_signal == signal)\n",
                "    print(f'    {CONFIRM_TF}: {confirm_signal} [{\"AGREE\" if agree else \"CONFLICT\"}]')\n",
                "    print(f'    Confidence: {fc_confirm[\"confidence\"]:.0f}%')\n",
                "\n",
                "# 4. Smart SL Calculation\n",
                "print('\\n[4] Smart Stop Loss Calculation...')\n",
                "cur_price = float(entry_df['close'].iloc[-1])\n",
                "sl, atr = smart_stop_loss(entry_df, fc['direction'], fc['confidence'], pattern_quality, support)\n",
                "tp = cur_price + (cur_price - sl) * RR_RATIO if fc['direction'] == 1 else cur_price - (sl - cur_price) * RR_RATIO\n",
                "\n",
                "sl_distance = abs(cur_price - sl)\n",
                "rr = abs(tp - cur_price) / sl_distance if sl_distance > 0 else 0\n",
                "\n",
                "print(f'    ATR: {atr:.5f}')\n",
                "print(f'    SL: {sl:.5f} ({sl_distance:.5f} pts = {sl_distance/atr:.2f}x ATR)')\n",
                "print(f'    TP: {tp:.5f} ({abs(tp-cur_price):.5f} pts)')\n",
                "print(f'    R:R: 1:{rr:.2f}')\n",
                "\n",
                "# 5. Final Signal\n",
                "print('\\n' + '='*70)\n",
                "if fc and fc['confidence'] > BASE_CONFIDENCE and rr >= MIN_RR:\n",
                "    print(f'SIGNAL: {signal} XAUUSD [1H]')\n",
                "    print(f'Confidence: {fc[\"confidence\"]:.0f}%')\n",
                "    print(f'Entry: {cur_price:.5f}')\n",
                "    print(f'SL: {sl:.5f}')\n",
                "    print(f'TP: {tp:.5f}')\n",
                "    print(f'R:R: 1:{rr:.2f}')\n",
                "    print(f'Pattern Quality: {pattern_quality:.0%}')\n",
                "else:\n",
                "    print(f'[SKIP] Confidence {fc[\"confidence\"]:.0f}% < {BASE_CONFIDENCE}% OR R:R {rr:.2f} < {MIN_RR}')\n",
                "print('='*70)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "id": "live_scanner",
            "metadata": {},
            "outputs": [],
            "source": [
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "# LIVE SCANNER\n",
                "# ═══════════════════════════════════════════════════════════════════════════════\n",
                "\n",
                "if 'live_stop' not in dir():\n",
                "    live_stop = threading.Event()\n",
                "\n",
                "if LIVE:\n",
                "    print(f'\\n[LIVE] Scanner ON | Interval: {SCAN_INTERVAL_S}s')\n",
                "    print('[LIVE] Press Ctrl+C to stop')\n",
                "    \n",
                "    def live_worker():\n",
                "        count = 0\n",
                "        while not live_stop.is_set():\n",
                "            try:\n",
                "                count += 1\n",
                "                now = datetime.now(timezone.utc).strftime('%H:%M:%S')\n",
                "                print(f'\\n[{now}][{count:3d}] Scanning...')\n",
                "                \n",
                "                # Fetch data\n",
                "                yf_sym = SYMBOL_MAP.get(ASSET, ASSET)\n",
                "                df = yf.download(yf_sym, period='7d', interval='1h', progress=False)\n",
                "                if df.empty:\n",
                "                    print('  [ERROR] Download failed')\n",
                "                    time.sleep(SCAN_INTERVAL_S)\n",
                "                    continue\n",
                "                \n",
                "                df.columns = [c.lower() for c in df.columns]\n",
                "                \n",
                "                # Generate signal\n",
                "                fc = ensemble_forecast(df)\n",
                "                if fc is None:\n",
                "                    print('  [SKIP] Forecast failed')\n",
                "                    time.sleep(SCAN_INTERVAL_S)\n",
                "                    continue\n",
                "                \n",
                "                if fc['confidence'] > BASE_CONFIDENCE:\n",
                "                    signal = 'BUY' if fc['direction'] > 0 else 'SELL'\n",
                "                    cur_price = float(df['close'].iloc[-1])\n",
                "                    sl, atr = smart_stop_loss(df, fc['direction'], fc['confidence'], 0.5, None)\n",
                "                    tp = cur_price + (cur_price - sl) * RR_RATIO if fc['direction'] == 1 else cur_price - (sl - cur_price) * RR_RATIO\n",
                "                    rr = abs(tp - cur_price) / abs(cur_price - sl) if abs(cur_price - sl) > 0 else 0\n",
                "                    \n",
                "                    print(f'  SIGNAL: {signal}')\n",
                "                    print(f'  Conf: {fc[\"confidence\"]:.0f}% | Entry: {cur_price:.5f} | SL: {sl:.5f} | TP: {tp:.5f} | R:R: 1:{rr:.2f}')\n",
                "                \n",
                "                time.sleep(SCAN_INTERVAL_S)\n",
                "            except Exception as e:\n",
                "                print(f'  [ERROR] {str(e)[:60]}')\n",
                "                time.sleep(SCAN_INTERVAL_S)\n",
                "    \n",
                "    live_stop.clear()\n",
                "    worker = threading.Thread(target=live_worker, daemon=True)\n",
                "    worker.start()\nelse:\n",
                "    print('\\n[CONFIG] Live scanner OFF (set LIVE=True to enable)')"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

# Save notebook
nb_path = Path("notebooks/05_signal_engine.ipynb")
with open(nb_path, 'w') as f:
    json.dump(notebook, f, indent=1)

print(f"[OK] Created {nb_path}")
print(f"     - LSTM + XGBoost ensemble")
print(f"     - ML Pattern Recognition (candlesticks, support/resistance, breakouts)")
print(f"     - Smart Stop Loss (volatility + pattern + support-based)")
print(f"     - Multi-timeframe confirmation")
print(f"     - Live scanning system")
